"""Weekly digest: one push that puts the finished US week in context.

Reads published pipeline data (market breadth, RRG prices, index valuation)
and a bounded set of EODHD daily bars, saves that evidence, then renders the
audit Markdown and the Feishu card from it. Like the daily reports, the
summary is rule-based and descriptive; nothing is generated by an LLM.
"""
from __future__ import annotations

import asyncio
from datetime import date, datetime, timedelta, timezone
import logging
from typing import Any

from sqlalchemy import desc, select

from core.config import settings
from core.trading_calendar import is_us_market_session, latest_completed_us_session, us_market_close_utc
from database import async_session_maker
from models import DailyReportRun, DataPublication, MarketBreadthSnapshot, PipelineRun
from services import eodhd_client
from services.analyzer import get_rrg_data_for_tickers
from services.daily_reporter import (
    _create_report_run,
    _finish_report_run,
    _record_rendered_report,
    _record_report_evidence,
)
from services.decision_support import midrank_percentile
from services.index_valuation import IndexValuationUnavailable, get_index_valuation
from services.notifications import NotificationManager
from services.notifications.report_card import build_weekly_card
from services.report_insights import SECTOR_SHORT, pct, weekly_headline
from services.report_market import NY, SECTOR_NAMES, collect_events, number, report_instruments
from services.report_renderer import grouped_events, value
from services.rrg_prices import RRG_SECTOR_NAMES
from services.watchlist_signals import price_signals, signal_tags


logger = logging.getLogger(__name__)
WEEKLY_REPORT_TYPE = "weekly_digest"
WEEKLY_RENDERER_VERSION = "weekly-v1"
WEEKLY_ASSETS = (
    ("SPY.US", "标普500", "USD"), ("QQQ.US", "纳指100", "USD"), ("IWM.US", "罗素2000", "USD"),
    ("VIX.INDX", "VIX", "点"), ("GLD.US", "黄金", "USD"), ("TLT.US", "长期美债", "USD"),
    ("NYICDX.INDX", "美元指数", "点"), ("BTC-USD.CC", "比特币", "USD"),
)
QUADRANT_NAMES = {"leading": "领先", "weakening": "转弱", "lagging": "落后", "improving": "改善"}
BREADTH_MAX_AGE_DAYS = 7
FETCH_BUDGET_SECONDS = 60


def last_closed_session(now: datetime) -> date:
    """Today once the NYSE has closed, otherwise the previous session."""
    today = now.astimezone(NY).date()
    if is_us_market_session(today) and now.astimezone(timezone.utc).replace(tzinfo=None) >= us_market_close_utc(today):
        return today
    return latest_completed_us_session(today)


def week_window(week_end: date) -> tuple[date, date]:
    """First session of week_end's calendar week, and the close before it."""
    monday = week_end - timedelta(days=week_end.weekday())
    sessions = [monday + timedelta(days=offset) for offset in range(week_end.weekday() + 1)]
    week_start = next(day for day in sessions if is_us_market_session(day))
    return week_start, latest_completed_us_session(week_start)


def weekly_change(rows: list[dict], week_end: date, previous: date) -> dict[str, Any]:
    """Close-to-close change; adjusted closes when both ends carry them."""
    by_date: dict[str, dict] = {}
    for row in rows or []:
        if not isinstance(row, dict) or number(row.get("close")) is None or number(row["close"]) <= 0:
            continue
        try:
            by_date[date.fromisoformat(str(row.get("date"))).isoformat()] = row
        except ValueError:
            continue
    current_keys = [key for key in by_date if key <= week_end.isoformat()]
    previous_keys = [key for key in by_date if key <= previous.isoformat()]
    if not current_keys:
        return {"price": None, "change_pct": None, "as_of": None}
    current_key = max(current_keys)
    result: dict[str, Any] = {"price": float(by_date[current_key]["close"]), "change_pct": None, "as_of": current_key}
    if not previous_keys or max(previous_keys) >= current_key:
        return result
    previous_key = max(previous_keys)
    end, start = by_date[current_key], by_date[previous_key]
    adjusted = all(number(row.get("adjusted_close")) and number(row["adjusted_close"]) > 0 for row in (end, start))
    basis = "adjusted_close" if adjusted else "close"
    result.update(change_pct=round((float(end[basis]) / float(start[basis]) - 1) * 100, 4),
                  previous_date=previous_key, basis=basis)
    return result


async def _weekly_quotes(items: list[dict], week_end: date, previous: date) -> list[dict]:
    results = {item["ticker"]: {**item, "price": None, "change_pct": None, "as_of": None} for item in items}
    semaphore = asyncio.Semaphore(4)
    async with eodhd_client.create_http_client() as client:
        async def fetch(item: dict) -> None:
            async with semaphore:
                try:
                    rows = await asyncio.wait_for(eodhd_client.get_eod_historical_data(
                        item["ticker"], (previous - timedelta(days=10)).isoformat(), week_end.isoformat(),
                        client=client), 10)
                    results[item["ticker"]] = {**item, **weekly_change(rows or [], week_end, previous)}
                except Exception as exc:
                    logger.warning("Weekly bars unavailable for %s (%s)", item["ticker"], type(exc).__name__)
        try:
            await asyncio.wait_for(asyncio.gather(*(fetch(item) for item in items)), FETCH_BUDGET_SECONDS)
        except TimeoutError:
            logger.warning("Weekly bar budget exhausted; keeping completed rows")
    return [results[item["ticker"]] for item in items]


def quadrant(point: dict) -> str:
    ratio, momentum = number(point.get("rs_ratio")), number(point.get("rs_momentum"))
    if ratio is None or momentum is None:
        return "unknown"
    if ratio >= 100:
        return "leading" if momentum >= 100 else "weakening"
    return "improving" if momentum >= 100 else "lagging"


async def _rrg(previous: date) -> dict | None:
    async with async_session_maker() as db:
        payload = await get_rrg_data_for_tickers(list(RRG_SECTOR_NAMES), db, benchmark="SPY.US", history_days=15)
    if not payload.get("data_complete") or not payload.get("data_as_of_date"):
        return None
    tickers = {name: ticker for ticker, name in RRG_SECTOR_NAMES.items()}
    items = []
    for name, series in payload.get("data", {}).items():
        if not series or name not in tickers:
            continue
        before = next((point for point in reversed(series) if str(point["date"])[:10] <= previous.isoformat()), None)
        items.append({"ticker": tickers[name], "quadrant": quadrant(series[-1]),
                      "previous_quadrant": quadrant(before) if before else None,
                      "rs_ratio": round(series[-1]["rs_ratio"], 2), "rs_momentum": round(series[-1]["rs_momentum"], 2)})
    return {"as_of": str(payload["data_as_of_date"])[:10], "previous_date": previous.isoformat(), "items": items}


async def _breadth(week_end: date, previous: date) -> dict | None:
    async with async_session_maker() as db:
        publication = await db.scalar(
            select(DataPublication)
            .join(PipelineRun, PipelineRun.id == DataPublication.pipeline_run_id)
            .where(DataPublication.dataset == "market_breadth", DataPublication.status == "published",
                   PipelineRun.status == "published")
            .order_by(desc(DataPublication.as_of_date)).limit(1))
        if publication is None:
            return None
        rows = list((await db.execute(
            select(MarketBreadthSnapshot)
            .where(MarketBreadthSnapshot.pipeline_run_id == publication.pipeline_run_id,
                   MarketBreadthSnapshot.universe == "SP500", MarketBreadthSnapshot.date <= week_end)
            .order_by(desc(MarketBreadthSnapshot.date)).limit(15))).scalars())
    if not rows or (week_end - rows[0].date).days > BREADTH_MAX_AGE_DAYS:
        return None
    latest = rows[0]
    before = next((row for row in rows if row.date <= previous), None)

    def share(row, period):
        eligible = getattr(row, f"ma{period}_eligible")
        return round(getattr(row, f"above_ma{period}") / eligible * 100, 2) if row and eligible else None

    week = [row for row in rows if previous < row.date <= latest.date]
    return {
        "as_of": latest.date.isoformat(), "previous_date": before.date.isoformat() if before else None,
        "pct_above_ma50": share(latest, 50), "pct_above_ma200": share(latest, 200),
        "previous_pct_above_ma50": share(before, 50), "previous_pct_above_ma200": share(before, 200),
        "new_highs": latest.new_high_count, "new_lows": latest.new_low_count,
        "net_advances": sum(row.advances - row.declines for row in week) if week else None,
    }


async def _valuation() -> dict | None:
    try:
        async with async_session_maker() as db:
            payload = await get_index_valuation(db, "SP500")
    except IndexValuationUnavailable:
        return None  # Not yet published; the card reports the gap once.
    points = [point for point in payload.get("points", []) if number(point.get("index_pe")) is not None]
    if not points:
        return None
    latest = points[-1]
    values = [point["index_pe"] for point in points]
    return {"as_of": latest["date"], "index_pe": latest["index_pe"], "months": len(values),
            "percentile": round(midrank_percentile(latest["index_pe"], values), 1),
            "stale": bool(payload.get("meta", {}).get("stale"))}


async def collect_weekly_evidence(now: datetime | None = None) -> dict[str, Any]:
    now = (now or datetime.now(timezone.utc)).astimezone(timezone.utc)
    week_end = last_closed_session(now)
    week_start, previous = week_window(week_end)
    warnings: list[str] = []

    async def optional(label: str, operation, timeout: float = 45):
        try:
            return await asyncio.wait_for(operation, timeout)
        except Exception as exc:
            logger.warning("Weekly %s unavailable (%s)", label, type(exc).__name__)
            warnings.append(f"{label}读取失败")
            return None

    instruments, instrument_warnings = await report_instruments()
    warnings.extend(instrument_warnings)
    core = [asset for asset in instruments if asset.group == "core"]
    asset_items = [{"ticker": ticker, "name": name, "currency": currency, "group": "asset"}
                   for ticker, name, currency in WEEKLY_ASSETS]
    sector_items = [{"ticker": ticker, "name": SECTOR_NAMES.get(ticker, ticker), "currency": "USD", "group": "sector"}
                    for ticker in RRG_SECTOR_NAMES] + [{"ticker": "RSP.US", "name": "标普等权", "currency": "USD", "group": "structure"}]
    core_items = [{"ticker": asset.ticker, "name": asset.name, "currency": asset.currency, "group": "core"} for asset in core]
    next_monday = week_end + timedelta(days=7 - week_end.weekday())

    quotes, rrg, breadth, valuation, signals, events = await asyncio.gather(
        _weekly_quotes(asset_items + sector_items + core_items, week_end, previous),
        optional("板块轮动", _rrg(previous)),
        optional("市场宽度", _breadth(week_end, previous)),
        optional("指数估值", _valuation()),
        optional("关注列表信号", price_signals([asset.ticker for asset in core], week_end), 60),
        optional("下周日历", collect_events(core, now, start=next_monday, end=next_monday + timedelta(days=4))),
    )
    by_ticker = {row["ticker"]: row for row in quotes}
    rsp, spy = by_ticker.get("RSP.US", {}), by_ticker.get("SPY.US", {})
    relative = None
    if number(rsp.get("change_pct")) is not None and number(spy.get("change_pct")) is not None \
            and rsp.get("as_of") == spy.get("as_of") == week_end.isoformat():
        relative = round(((1 + rsp["change_pct"] / 100) / (1 + spy["change_pct"] / 100) - 1) * 100, 4)
    stale = [row["name"] for row in quotes if row["group"] != "core" and not row["ticker"].endswith(".CC")
             and row.get("as_of") != week_end.isoformat()]
    if stale:
        warnings.append(f"{len(stale)} 项周线未覆盖到 {week_end.isoformat()}：{'、'.join(stale[:4])}")
    return {
        "schema_version": 1, "captured_at": now.isoformat(),
        "week_start": week_start.isoformat(), "week_end": week_end.isoformat(), "previous_close_date": previous.isoformat(),
        "assets": [row for row in quotes if row["group"] == "asset"],
        "sectors": [row for row in quotes if row["group"] == "sector"],
        "rsp_relative_pct": relative, "rrg": rrg, "breadth": breadth, "valuation": valuation,
        "watchlist": [row for row in quotes if row["group"] == "core"],
        "watchlist_signals": signals, "events": events, "warnings": warnings,
    }


def render_weekly_markdown(digest: dict) -> str:
    """Audit text: everything the card shows, with dates and bases spelled out."""
    lines = [f"**美股周报｜{digest['week_start']} 至 {digest['week_end']}**", "",
             f"周涨跌相对 {digest['previous_close_date']} 收盘；数据来自 EODHD 日线及已发布的流水线。", "",
             f"结论（规则生成）：{weekly_headline(digest)}", "", "**主要资产**", ""]

    def quote(row: dict) -> str:
        if number(row.get("price")) is None:
            return f"- {row['name']}（{row['ticker']}）：数据不可用"
        basis = "复权" if row.get("basis") == "adjusted_close" else "收盘价"
        return (f"- {row['name']}（{row['ticker']}）：{value(row['price'])} / {pct(row.get('change_pct'))}"
                f"（{row.get('previous_date') or '无对比日'} → {row['as_of']}，{basis}）")

    lines.extend(quote(row) for row in digest.get("assets", []))
    lines.extend(["", "**板块周涨跌**", ""])
    sectors = sorted(digest.get("sectors", []), key=lambda row: -(number(row.get("change_pct")) or -1e9))
    lines.extend(quote(row) for row in sectors)
    if digest.get("rsp_relative_pct") is not None:
        lines.append(f"- 等权 RSP 相对 SPY：{pct(digest['rsp_relative_pct'])}")
    rrg = digest.get("rrg")
    lines.extend(["", "**板块轮动（RRG，相对 SPY）**", ""])
    if rrg:
        lines.append(f"截至 {rrg['as_of']}，对比 {rrg['previous_date']}。")
        for item in rrg["items"]:
            moved = "" if item.get("previous_quadrant") in (None, item["quadrant"]) else \
                f"（上周 {QUADRANT_NAMES.get(item['previous_quadrant'], '未知')}）"
            lines.append(f"- {SECTOR_SHORT.get(item['ticker'], item['ticker'])}：{QUADRANT_NAMES.get(item['quadrant'], '未知')}{moved}"
                         f"；RS-Ratio {item.get('rs_ratio')} / RS-Momentum {item.get('rs_momentum')}")
    else:
        lines.append("- 板块轮动暂不可用。")
    lines.extend(["", "**市场温度**", ""])
    breadth = digest.get("breadth")
    if breadth:
        lines.append(f"- 标普500 宽度截至 {breadth['as_of']}（对比 {breadth.get('previous_date') or '无'}）："
                     f"站上 MA50 {value(breadth.get('pct_above_ma50'), '%')}（上周 {value(breadth.get('previous_pct_above_ma50'), '%')}）；"
                     f"站上 MA200 {value(breadth.get('pct_above_ma200'), '%')}（上周 {value(breadth.get('previous_pct_above_ma200'), '%')}）；"
                     f"52周新高 {breadth.get('new_highs')} / 新低 {breadth.get('new_lows')}；本周涨跌家数差 {breadth.get('net_advances')}")
    else:
        lines.append("- 市场宽度暂不可用。")
    valuation = digest.get("valuation")
    if valuation:
        lines.append(f"- 标普500 P/E {value(valuation['index_pe'], digits=1)}（{valuation['as_of']} 月末，历史重建估算），"
                     f"位于 {valuation['months']} 个月序列的 {value(valuation.get('percentile'), '%', digits=0)} 分位。")
    else:
        lines.append("- 指数估值暂不可用。")
    lines.extend(["", "**关注列表（周涨跌）**", ""])
    signals = digest.get("watchlist_signals")
    for row in digest.get("watchlist", []):
        tags = "；".join(tag["text"] for tag in signal_tags(row["ticker"], signals))
        lines.append(quote(row) + (f"；{tags}" if tags else ""))
    events = digest.get("events") or {}
    lines.extend(["", "**下周关注**", ""])
    if events.get("economic_available") or events.get("earnings_available"):
        lines.append(f"窗口 {events['from']} 至 {events['to']}；{events.get('timezone_note', '')}")
        lines.extend(grouped_events(events.get("items", [])) or ["- 未发现匹配的重要美国经济事件或关注列表财报。"])
    else:
        lines.append("- 日历暂不可用，不能据此判断没有重要事件。")
    if digest.get("warnings"):
        lines.extend(["", "**数据提示**", ""])
        lines.extend(f"- {warning}" for warning in digest["warnings"])
    lines.extend(["", "说明：结论按固定规则由数据生成，只描述涨跌，不推断原因，也不构成投资建议。"])
    return "\n".join(lines)


async def _already_delivered(week_end: str) -> bool:
    async with async_session_maker() as db:
        found = await db.scalar(
            select(DailyReportRun.id)
            .where(DailyReportRun.report_type == WEEKLY_REPORT_TYPE, DailyReportRun.status == "delivered",
                   DailyReportRun.market_context["week_end"].as_string() == week_end)
            .limit(1))
    return found is not None


def build_weekly_report_card(digest: dict, tag: str | None = None) -> dict:
    return build_weekly_card(digest, headline=weekly_headline(digest),
                             site_url=settings.PUBLIC_SITE_URL.rstrip("/"), tag=tag)


async def generate_weekly_digest(now: datetime | None = None) -> dict[str, Any]:
    now = now or datetime.now(timezone.utc)
    expected = last_closed_session(now)
    if await _already_delivered(expected.isoformat()):
        return {"status": "skipped", "reason": "already-delivered", "week_end": expected.isoformat()}

    report_run_id = await _create_report_run(report_type=WEEKLY_REPORT_TYPE, renderer_version=WEEKLY_RENDERER_VERSION)
    try:
        digest = await collect_weekly_evidence(now)
    except Exception as exc:
        await _finish_report_run(report_run_id, status="evidence_failed", delivered=False, error_message=str(exc))
        raise
    if not any(number(row.get("change_pct")) is not None for row in digest["assets"] + digest["sectors"]):
        await _record_report_evidence(report_run_id, [], digest)
        await _finish_report_run(report_run_id, status="evidence_failed", delivered=False,
                                 error_message="No weekly price change was available")
        raise RuntimeError("Weekly digest has no usable price evidence")
    await _record_report_evidence(report_run_id, [], digest)
    content = render_weekly_markdown(digest)
    card = build_weekly_report_card(digest)
    await _record_rendered_report(report_run_id, content)
    try:
        delivered = await NotificationManager.broadcast(title="📅 Quantify 美股周报", content=content, card=card)
        if not delivered:
            raise RuntimeError("No notification channel accepted the weekly digest")
    except Exception as exc:
        await _finish_report_run(report_run_id, status="delivery_failed", delivered=False, error_message=str(exc))
        raise
    await _finish_report_run(report_run_id, status="delivered", delivered=True)
    return {"status": "delivered", "report_type": WEEKLY_REPORT_TYPE, "report_run_id": report_run_id,
            "week_end": digest["week_end"]}
